### ISSUE TITLE
'compress-cra' is not recognized

### ISSUE THREAD

**Issue by iPramodSinghRawat** [jnsjknn/compress-create-react-app#2] opened 2021-08-31 12:53 UTC
npm run build results in 
'compress-cra' is not recognized as an internal or external command, operable program or batch file.

**Comment by jnsjknn** [comment] 2021-08-31 21:01
Hi @iPramodSinghRawat,

Do you have your project visible on GitHub or is there some way I could get it on my device so that I could try to reproduce the issue? 

Have you tried reinstalling the package?

**Comment by PsiKai** [comment] 2021-10-09 18:09
@iPramodSinghRawat I am having the same issue.  I have a pretty generic create-react-app, and have not modified any scripts in the client `package.json`.  When I run the build command configured as the documentation instructs I get this output:
```
Compiled successfully.

File sizes after gzip:

  163.63 KB  build\static\js\2.3a459516.chunk.js
  22.65 KB   build\static\css\2.beec3579.chunk.css
  6.23 KB    build\static\js\main.50c7cfde.chunk.js
  4.57 KB    build\static\css\main.94090ce8.chunk.css
  776 B      build\static\js\runtime-main.d594e05a.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment

'compress-cra' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! day-plan-react@0.1.0 build: `react-scripts build && compress-cra`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the day-plan-react@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm-cache\_logs\2021-10-09T17_57_53_633Z-debug.log
```

The repository can be found at https://github.com/PsiKai/leather-planner.

I have a PR open with the modifications to the `package.json`, but as I mentioned, that is the only configuration I have changed.

I did, however, install the package in my app root, which is where my node.js server lives.  So the root `package.json` will be in the root, where you can see that I installed the package as a dev dependency.

**Comment by jnsjknn** [comment] 2021-10-10 12:18
Hi @PsiKai,

I'm glad you found an alternative solution and got it to work for you. I believe the problem you had was caused by installing compress-CRA for the client (client/package.json) and adding the command for your server (<root>/package.json).

Both the command and the dependency should be added for the client, a CRA app.

**Comment by PsiKai** [comment] 2021-10-10 16:52
- @jnsjknn Thanks for the response! I think you are right, except it was opposite, because I had the package installed for the backend `package.json` and tried to use the command in the client `package.json`. Next time I will try it as you have instructed.

I definitely get mixed up sometimes trying to manage the two different json files. That's probably my only complaint about the MERN stack.

**Closed** 2022-03-23 08:27 UTC
